name: Trigger csvcubed update in gss-utils
on:
  workflow_call:

jobs:
  Trigger_gss-utils_workflow:
    name: Trigger_gss-utils_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: gh workflow run updateCsvcubedPackage.yaml --repo github.com/GSS-Cogs/gss-utils
        env:
          GITHUB_TOKEN: ${{ secrets.CSVCUBED_GSS_UTILS_PR_API_TOKEN }}
          
